apiVersion: v3
kind: service
metadata:
  name: juli1-github-test
spec:
  lifecycle: test
  tier: "1"
  type: web
datadog:
  codeLocations:
    - repositoryURL: https://github.com/juli1/playground.git
      paths:
        - /foo/bar/baz/**
